Add instructions for resolving validation failures:
* Add instructions to the workflow at the point where the failure would
  occur, which is where someone experiencing a failure is most likely to
  look. To keep things simple, the instructions are always printed. The
  assumption is that if the job succeeds, nobody is likely to look
  anyway.
* Provides the diff of the failure as an artifact, so the user can apply
  it directly to their repo.
* Also update the levelization/README.md to clarify the levels a little
  bit.

diff --git a/.github/workflows/clang-format.yml b/.github/workflows/clang-format.yml
--- a/.github/workflows/clang-format.yml
+++ b/.github/workflows/clang-format.yml
@@ -23,5 +23,31 @@ jobs:
     - name: Format src/test
       run: find src/test -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.ipp' \) -print0 | xargs -0 clang-format-${CLANG_VERSION} -i
     - name: Check for differences
-      run: git diff --exit-code
+      shell: bash
+      run: |
+        set -o pipefail
+        echo "If you are reading this, you are probably looking at a failed"
+        echo "Github Actions job. That means you pushed a file that did not"
+        echo "conform to the formatting specified in .clang-format. That may"
+        echo "be because you neglected to run 'git clang-format' or "
+        echo "'clang-format' before committing, or that your version of"
+        echo "clang-format has an incompatibility with the one on this"
+        echo "machine, which is:"
+        clang-format-${CLANG_VERSION} --version
+        echo
+        echo "To fix it, you can do one of two things:"
+        echo "1. (The hard way): Download and apply the patch generated as an"
+        echo "   artifact of this job to your repo, commit, and push."
+        echo "2. (The easy way): Run "
+        echo "   'git-clang-format --extensions c,cpp,h,cxx,ipp develop'"
+        echo "   in your repo, commit, and push."
+        git diff --exit-code | tee "${{ github.sha }}.patch"
+    - name: Publish patch
+      if: failure()
+      uses: actions/upload-artifact@v2
+      continue-on-error: true
+      with:
+        name: ${{ github.sha }}.patch
+        if-no-files-found: ignore
+        path: ${{ github.sha }}.patch
 
diff --git a/.github/workflows/levelization.yml b/.github/workflows/levelization.yml
--- a/.github/workflows/levelization.yml
+++ b/.github/workflows/levelization.yml
@@ -12,7 +12,34 @@ jobs:
     - name: Check levelization
       run: Builds/levelization/levelization.sh
     - name: Check for differences
-      run: git diff --exit-code
-      # If this workflow fails, and you have improved levelization, run
-      # Builds/levelization/levelization.sh, and commit the changes to
-      # loops.txt.
+      shell: bash
+      run: |
+        set -o pipefail
+        echo "If you are reading this, you are probably looking at a failed"
+        echo "Github Actions job. That means you changed the dependency"
+        echo "relationships between the modules in rippled. That may be an"
+        echo "improvement or a regression. This check doesn't judge."
+        echo
+        echo "A rule of thumb, though, is that if you removed something from"
+        echo "loops.txt, that's probably an improvement. If you added"
+        echo "something, it's probably a regression."
+        echo
+        echo "To fix it, you can do one of two things:"
+        echo "1. (The hard way): Download and apply the patch generated as an"
+        echo "   artifact of this job to your repo, commit, and push."
+        echo "2. (The easy way): Run './Builds/levelization/levelization.sh'"
+        echo "   in your repo, commit, and push."
+        echo
+        echo "See Builds/levelization/README.md for more info."
+        git diff --exit-code | tee "${{ github.sha }}.patch"
+        # If this workflow fails, and you have improved levelization, run
+        # Builds/levelization/levelization.sh, and commit the changes to
+        # loops.txt.
+    - name: Publish patch
+      if: failure()
+      uses: actions/upload-artifact@v2
+      continue-on-error: true
+      with:
+        name: ${{ github.sha }}.patch
+        if-no-files-found: ignore
+        path: ${{ github.sha }}.patch
