[FOLD] Restructure MacOS caches

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -5,9 +5,7 @@ env:
   NINJA_BUILD: true
   CACHE_DIR: ${{ github.workspace }}/_cache
   NIH_CACHE_ROOT: ${{ github.workspace }}/_cache/nih_c
-  # put NIH in non-cache location since it seems to
-  # cause failures when homebrew updates
-  # NIH_CACHE_ROOT: ${{ github.workspace }}/nih_c
+  NIH_SRC_PATH: ${{ github.workspace }}/_srccache
   PARALLEL_TESTS: true
   USE_CCACHE: true
   CCACHE_BASEDIR: ${{ github.workspace }}
@@ -30,7 +28,7 @@ env:
 
 jobs:
   macos_cache:
-    name: Seed MacOS cache
+    name: Seed MacOS dependencies
     runs-on: "macos-latest"
     timeout-minutes: 720
     if: ${{ !contains(github.event.head_commit.message, 'ci_run_') || contains(github.event.head_commit.message, 'ci_run_mac') }}
@@ -96,19 +94,22 @@ jobs:
           echo "::set-output name=brewinfo::${{ hashfiles('brew.info') }}"
 
       - name: Boost cache
+        id: boostcache
         continue-on-error: true
         uses: actions/cache@v2
         with:
           path: ${{ env.BOOST_ROOT }}
           key: ${{ runner.os }}-boost-${{ env.BOOST_ROOT }}
 
-      - name: Build cache
-        id: nihcache
+      - name: Source cache
+        id: srccache
         continue-on-error: true
         uses: actions/cache@v2
         with:
-          path: ${{ env.CACHE_DIR }}
-          key: ${{ runner.os }}-nih-${{ steps.brew.outputs.brewinfo }}-${{ steps.cachekeys.outputs.cmakeconfig }}-${{ steps.cachekeys.outputs.instructions }}
+          path: ${{ env.NIH_SRC_PATH}}
+          key: ${{ runner.os }}-nihsrc-${{ steps.cachekeys.outputs.cmakeconfig }}-${{ steps.cachekeys.outputs.instructions }}
+          restore-keys: |
+            ${{ runner.os }}-nihsrc-${{ steps.cachekeys.outputs.cmakeconfig }}-
 
       - name: Dump environment
         run: |
@@ -134,6 +135,7 @@ jobs:
           echo "::set-output name=CXX::$(brew --prefix llvm)/bin/clang++"
 
       - name: Build boost
+        if: steps.boostcache.outputs.cache-hit != 'true'
         shell: bash
         env:
           CC: ${{ steps.pre.outputs.CC }}
@@ -148,50 +150,67 @@ jobs:
           ./Builds/containers/shared/install_boost.sh
           # brew uninstall --ignore-dependencies boost
 
-      - name: Initialize CMake cache
-        if: ${{ ! steps.nihcache.outputs.cache-hit }}
+      - name: Download CMake dependencies
+        if: steps.srccache.outputs.cache-hit != 'true'
         shell: bash
         env:
           CC: ${{ steps.pre.outputs.CC }}
           CXX: ${{ steps.pre.outputs.CXX }}
           NUM_PROCESSORS: ${{ steps.pre.outputs.NUM_PROCESSORS }}
-          BLD_CONFIGS: "Debug Release"
         run: |
-            if [[ -e "${NIH_CACHE_ROOT}" ]]
-            then
-                echo Cache is already set up.
-                exit
-            fi
-
             cmake --version
             ${CC} --version
             ${CXX} --version
 
-            [[ "${verbose}" == "true" ]] && set -x || true
+            export BLD_CONFIG=Debug
 
-            for BLD_CONFIG in ${BLD_CONFIGS}
+            ${CC} --version
+            ${CXX} --version
+            dir="${builddir}/$( basename ${CXX} ).${BLD_CONFIG}"
+            mkdir "-pv" "${dir}"
+            pushd "${dir}"
+            # Verbose or not, it's good to see the right params
+            # are being used
+            set "-x"
+            # rm is called if the first cmake fails, because the most
+            # likely cause is cache mismatch or corruption. If that happens
+            # reset the cache and try again.
+            cmake -DCMAKE_BUILD_TYPE=${BLD_CONFIG} \
+                ${CMAKE_ARGS} ${srcdir} || \
+                ( rm -rf ${{ env.CACHE_DIR }} ${{ env.NIH_SRC_PATH }}; \
+                  cmake -DCMAKE_BUILD_TYPE=${BLD_CONFIG} \
+                    ${CMAKE_ARGS} ${srcdir} )
+
+            alldeps=( $( \
+                cmake --build . --target help | \
+                grep phony | cut -d: -f1 | \
+                sed 's/^\/.*\/rippled\/.*\/CMakeFiles\///' | \
+                grep -v -e '\/' -e '^all' -e install -e clean \
+                -e depend -e cache -e docs -e rippled -e xrpl_core \
+                -e container -e '^rpm' -e '^dpkg' \
+                ) )
+            echo "Building dependencies: ${alldeps[@]}"
+            for dep in help "${alldeps[@]}"
             do
-                export BLD_CONFIG
-                dir="${builddir}.${BLD_CONFIG}"
-                mkdir -pv "${dir}"
-                pushd "${dir}"
-                cmake -DCMAKE_BUILD_TYPE=${BLD_CONFIG} ${CMAKE_ARGS} ${srcdir}
-                popd
+                echo Building $dep
+                cmake --build . --target $dep --parallel
             done
+            set +x
 
-            du -sh ${CACHE_DIR}
-            find ${NIH_CACHE_ROOT} -maxdepth 2 \( -iname src -prune -o -type d -exec du -sh {} \; \)
+            popd
 
       - name: Disk space after
         shell: bash
         if: always()
         run: |
           df -h
-          find ${CACHE_DIR} -maxdepth 2 \( -iname src -prune -o \
-            -type d -exec du -sh {} \; \) || true
+          du -sh ${CACHE_DIR} || true
+          du -sh ${CCACHE_DIR} || true
+          find ${NIH_SRC_PATH} ${NIH_CACHE_ROOT} -maxdepth 2 \
+            -type d -exec du -sh {} \; || true
 
       - name: Debug output
-        if: ${{ ! steps.cache.outputs.cache-hit || failure() }}
+        if: steps.cache.outputs.cache-hit != 'true' || failure()
         shell: bash
         continue-on-error: true
         run: |
@@ -201,11 +220,11 @@ jobs:
             -name CMakeError.log \) -ls -exec cat {} \; ; fi
 
       - name: Debug output artifacts
-        if: ${{ ! steps.cache.outputs.cache-hit || failure() }}
+        if: steps.cache.outputs.cache-hit != 'true' || failure()
         uses: actions/upload-artifact@v2
         continue-on-error: true
         with:
-          name: debug-output NIH
+          name: debug-output NIH dependencies
           retention-days: 7
           if-no-files-found: ignore
           path: |
@@ -283,7 +302,14 @@ jobs:
             ${{ runner.os }}-${{ needs.macos_cache.outputs.cmakeconfig }}-${{ env.BLD_CONFIG }}-${{ needs.macos_cache.outputs.headers }}-${{ needs.macos_cache.outputs.source }}
             ${{ runner.os }}-${{ needs.macos_cache.outputs.cmakeconfig }}-${{ env.BLD_CONFIG }}-${{ needs.macos_cache.outputs.headers }}
             ${{ runner.os }}-${{ needs.macos_cache.outputs.cmakeconfig }}-${{ env.BLD_CONFIG }}
-            ${{ runner.os }}-nih-${{ needs.macos_cache.outputs.brewinfo }}-${{ needs.macos_cache.outputs.cmakeconfig }}
+
+      - name: Source cache
+        id: srccache
+        continue-on-error: true
+        uses: actions/cache@v2
+        with:
+          path: ${{ env.NIH_SRC_PATH}}
+          key: ${{ runner.os }}-nihsrc-${{ needs.macos_cache.outputs.cmakeconfig }}-${{ needs.macos_cache.outputs.instructions }}
 
       - name: Dump environment
         run: |
@@ -301,8 +327,9 @@ jobs:
         shell: bash
         run: |
           df -h
-          find ${CACHE_DIR} -maxdepth 2 \( -iname src -prune -o \
-            -type d -exec du -sh {} \; \) || true
+          du -sh ${CACHE_DIR} || true
+          find ${NIH_SRC_PATH} ${NIH_CACHE_ROOT} -maxdepth 2 \
+            -type d -exec du -sh {} \; || true
 
       - name: Build
         shell: bash
@@ -334,8 +361,9 @@ jobs:
         if: always()
         run: |
           df -h
-          find ${CACHE_DIR} -maxdepth 2 \( -iname src -prune -o \
-            -type d -exec du -sh {} \; \) || true
+          du -sh ${CACHE_DIR} || true
+          find ${NIH_SRC_PATH} ${NIH_CACHE_ROOT} -maxdepth 2 \
+            -type d -exec du -sh {} \; || true
 
       - name: Post-run ccache stats
         shell: bash
