Address review comments

diff --git a/.github/workflows/nix.yml b/.github/workflows/nix.yml
--- a/.github/workflows/nix.yml
+++ b/.github/workflows/nix.yml
@@ -12,7 +12,8 @@ on: [push, pull_request]
 # and builds and caches binaries for all the dependencies.
 # If an Artifactory remote is configured, they are cached there.
 # If not, they are added to the GitHub artifact.
-# GitHub's "cache" action has a size limit that is too small.
+# GitHub's "cache" action has a size limit (10 GB) that is too small
+# to hold the binaries if they are built locally.
 # We must use the "{upload,download}-artifact" actions instead.
 #
 # The second phase has a job in the matrix for each test configuration.
@@ -74,16 +75,15 @@ jobs:
           conan remote add ripple ${{ env.CONAN_URL }} --insert 0
       - name: try to authenticate to ripple Conan remote
         id: remote
-        continue-on-error: true
         run: |
-          conan user --remote ripple ${{ secrets.CONAN_USERNAME }} --password ${{ secrets.CONAN_TOKEN }}
+          echo outcome=$(conan user --remote ripple ${{ secrets.CONAN_USERNAME }} --password ${{ secrets.CONAN_TOKEN }} && echo success || echo failure) | tee ${GITHUB_OUTPUT}
       - name: archive profile
         # Create this archive before dependencies are added to the local cache.
         run: tar -czf conan.tar -C ~/.conan .
       - name: list missing binaries
         id: binaries
         # Print the list of dependencies that would need to be built locally.
-        # A non-zero number means we have "failed" to cache binaries remotely.
+        # A non-empty list means we have "failed" to cache binaries remotely.
         run: |
           echo missing=$(conan info . --build missing --json 2>/dev/null  | grep '^\[') | tee ${GITHUB_OUTPUT}
       - name: build dependencies
@@ -92,10 +92,10 @@ jobs:
         with:
           configuration: ${{ matrix.configuration }}
       - name: upload dependencies to remote
-        if: (steps.binaries.outputs.missing != '[]') && (steps.remote.outcome == 'success')
+        if: (steps.binaries.outputs.missing != '[]') && (steps.remote.outputs.outcome == 'success')
         run: conan upload --remote ripple '*' --all --parallel --confirm
       - name: recreate archive with dependencies
-        if: (steps.binaries.outputs.missing != '[]') && (steps.remote.outcome == 'failure')
+        if: (steps.binaries.outputs.missing != '[]') && (steps.remote.outputs.outcome == 'failure')
         run: tar -czf conan.tar -C ~/.conan .
       - name: upload archive
         uses: actions/upload-artifact@v3
