Change 'on: pull_request' to 'on: push' and use workaround to get PR number

diff --git a/.github/workflows/notify-clio.yml b/.github/workflows/notify-clio.yml
--- a/.github/workflows/notify-clio.yml
+++ b/.github/workflows/notify-clio.yml
@@ -30,7 +30,30 @@ env:
   CONAN_REMOTE_URL: https://conan.ripplex.io
 
 jobs:
+  pr:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+        with:
+          fetch-depth: 0
+      - name: Fetch PR number
+        id: cli
+        env:
+          GITHUB_TOKEN: ${{ secrets.clio_notify_token }}
+        run: |
+          echo "Fetching PR number associated with current commit '${{ github.sha }}'."
+          NUMBER=$(gh pr list --search ${{ github.sha }} --json number -q '[0] | .number' || echo '')
+          if [ -z "${NUMBER}" ]; then
+            echo 'Could not fetch PR number.'
+            exit 1
+          fi
+          echo "number=${NUMBER}" >> "${GITHUB_OUTPUT}"
+    outputs:
+      number: ${{ steps.cli.outputs.number }}
+
   upload:
+    needs: pr
     runs-on: ubuntu-latest
     container: ghcr.io/xrplf/ci/ubuntu-noble:gcc-13
     steps:
@@ -40,7 +63,7 @@ jobs:
         id: generate
         run: |
           echo "Generating channel."
-          echo channel="clio/pr_${{ github.event.pull_request.number }}" >> "${GITHUB_OUTPUT}"
+          echo channel="clio/pr_${{ needs.pr.outputs.number }}" >> "${GITHUB_OUTPUT}"
           echo "Extracting version."
           echo version="$(cat src/libxrpl/protocol/BuildInfo.cpp | grep "versionString =" | awk -F '"' '{print $2}')" >> "${GITHUB_OUTPUT}"
       - name: Add Conan remote
