[FOLD] Address review feedback from @thejohnfreeman:
* Experimentally remove the `-p` param from mkdir in dependencies action
* Add the "build_type" param to the dependencies check in the `nix` workflow
* Update the version of actions/cache
* Steal the remote step outcome fix from #4716
* Allow the Windows job to succeed if tests fail (explained in comments)

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -39,7 +39,7 @@ jobs:
           pip install --upgrade pip
           echo "dir=$(pip cache dir)" | tee ${GITHUB_OUTPUT}
       - name: restore Python cache directory
-        uses: actions/cache@v2
+        uses: actions/cache@v3
         with:
             path: ${{ steps.pip-cache.outputs.dir }}
             key: ${{ runner.os }}-${{ hashFiles('.github/workflows/windows.yml') }}
@@ -66,7 +66,8 @@ jobs:
         shell: bash
         id: remote
         run: |
-          echo outcome=$(conan user --remote ripple ${{ secrets.CONAN_USERNAME }} --password ${{ secrets.CONAN_TOKEN }} && echo success || echo failure) | tee ${GITHUB_OUTPUT}
+          conan user --remote ripple ${{ secrets.CONAN_USERNAME }} --password ${{ secrets.CONAN_TOKEN }}
+          echo outcome=$([ $? -eq 0 ] && echo success || echo failure) | tee ${GITHUB_OUTPUT}
       - name: list missing binaries
         id: binaries
         shell: bash
@@ -91,6 +92,12 @@ jobs:
           cmake-args: '-Dassert=ON -Dreporting=OFF -Dunity=OFF'
       - name: test
         shell: bash
+        # Github runners are resource limited, which causes unit tests to fail
+        # (e.g. OOM). To allow forward progress until self-hosted runners are
+        # up and running reliably, allow the job to succeed even if tests fail.
+        continue-on-error: true
         run: |
-          # ${build_dir}/${{ matrix.configuration }}/rippled --unittest --unittest-jobs $(nproc)
-          ${build_dir}/${{ matrix.configuration }}/rippled --unittest --unittest-jobs 1
+          # Remove these echo statements before merging
+          echo "nproc: $(nproc)"
+          echo "NUMBER_OF_PROCESSORS ${NUMBER_OF_PROCESSORS}"
+          ${build_dir}/${{ matrix.configuration }}/rippled --unittest --unittest-jobs $(nproc)
